name: test workflow 

on: 
  push: 
    branches: 
      - main 

jobs:
   build:
     runs-on: ubuntu-24.04
     steps:
       - name: checkout code 
         uses:  actions/checkout@v4

       - name: print the name 
         run: echo "Madhav"
       - name: running a test 
         run: echo "running an the tests"

         
         
      
