name: test 

on: 
 push:
   branches:
     - main 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code 
        uses: actions/checkout@v4

      - name: print the name 
        run: echo "Hello Madhav"

  prints:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkount 
        uses: actions/checkout@v4
      - name: print the OS name 
        run: echo " windows"
        
        
   
        
     
